#!/bin/bash
TMPROOT=/develop/tmp
TMPDIR=$(mktemp -p ${TMPROOT} -d git.XXXXXX)
TMPGEM=$(mktemp -p ${TMPROOT} -d gem.XXXXXX)

git clone $1 ${TMPDIR}

pushd ${TMPDIR}
export GEM_HOME=${TMPGEM}
$(getent passwd ${USER} | cut -d: -f7)
popd

rm -rf ${TMPDIR}
rm -rf ${TMPGEM}
